language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script: xvfb-run polymer test --module-resolution=node --npm --plugin local
cache:
  directories:
    - node_modules

