language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli
- polymer install
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test polymer test --plugin local
cache:
  directories:
  - node_modules
